name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  geolocator: ^7.6.2

dev_dependencies:
  flutter_spinkit: ^5.1.0
  flutter_test:
    sdk: flutter
  http: ^0.13.3

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
